sudo:  required
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - openssl aes-256-cbc -K $encrypted_d1fa5e9f9bde_key -iv $encrypted_d1fa5e9f9bde_iv -in service-account.json.enc -out service-account.json -d  
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project ardent-turbine-235804
  - gcloud config set compute/zone  us-west1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t eafolabi/multi-react-test -f ./client/Dockerfile.dev ./client
env:
  global:
     - SHA=$(git rev-parse HEAD)
     - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script:
  - docker run eafolabi/multi-react-test npm test -- --coverage


deploy:
  provider: script
  script: bash ./deploy.sh
  on: 
     branch: master
